import orcaProfiles from '../data/orca-profiles.json'
import type { OrcaConfig, SlicePreset } from '../types'

// orcaProfiles is generated by scripts/fetch-orca-profiles.ts from
// OrcaSlicer's own bundled profile tree (resources/profiles/<Vendor>/...),
// resolving each profile's `inherits` chain. Re-fetch with:
//   npx tsx scripts/fetch-orca-profiles.ts
export const PRESETS: SlicePreset[] = orcaProfiles.qualityPresets as SlicePreset[]

export const FILAMENT_PRESETS: Record<string, Partial<OrcaConfig>> = orcaProfiles.filamentPresets

// bed_size_x/y and printable_height are real values from OrcaSlicer's own
// bundled profiles (resources/profiles/<Vendor>/machine/*.json) — our
// headless WASM build ships none of these, so the web UI's presets are the
// only source of truth for them. printable_height in particular used to be
// missing entirely, silently falling back to the *engine's* generic
// FullPrintConfig default of 100mm (PrintConfig.cpp) — well under any of
// these printers' real Z height, so any model taller than 100mm failed
// "exceeds the maximum build volume height" validation regardless of which
// printer was selected.
export const PRINTER_PRESETS: Record<string, Partial<OrcaConfig>> = orcaProfiles.printerPresets

// UI display fallbacks for config fields a preset may leave unset. Display
// only — deliberately NOT merged into the engine config (an unset field must
// keep falling back to the engine's own default, which may differ). Having
// one table keeps every surface (settings inputs, config summary, 3D bed
// viewers) quoting the same number instead of each hardcoding its own.
export const DISPLAY_DEFAULTS = {
  printer_model: 'Generic',
  nozzle_diameter: 0.4,
  bed_size_x: 256,
  bed_size_y: 256,
  bed_shape: 'rectangle',
  filament_type: 'PLA',
  nozzle_temperature: 220,
  bed_temperature: 60,
  layer_height: 0.2,
  initial_layer_print_height: 0.2,
  top_shell_layers: 4,
  bottom_shell_layers: 3,
  wall_loops: 3,
  wall_generator: 'arachne',
  sparse_infill_density: 15,
  sparse_infill_pattern: 'grid',
  default_speed: 100,
  outer_wall_speed: 60,
  initial_layer_speed: 30,
  travel_speed: 150,
  seam_position: 'aligned',
  fuzzy_skin: 'none',
  fuzzy_skin_thickness: 0.3,
  fuzzy_skin_point_dist: 0.8,
  enable_support: false,
  support_type: 'normal(auto)',
  brim_width: 0,
  brim_type: 'auto_brim',
  skirt_loops: 1,
  skirt_distance: 2,
  raft_layers: 0,
} as const satisfies OrcaConfig

/**
 * Parse the current config's filament_type into its individual AMS-style
 * slots — OrcaSlicer represents a multi-material machine profile's filament
 * types as one semicolon/comma-joined string (e.g. "PLA;PETG;ABS;TPU"), one
 * entry per physical slot. A single-material config just returns one entry.
 * Shared by ConfigSummary (slot count/name display) and the per-object
 * filament-slot picker on the Slice tab (orc_slice_multi's extruder_ids —
 * see slicePlate() in useSliceQueue.ts) so both read the same slot list.
 */
export function filamentSlots(config: OrcaConfig): string[] {
  return String(config.filament_type ?? DISPLAY_DEFAULTS.filament_type)
    .split(/[;,]/)
    .map((entry) => entry.trim())
    .filter(Boolean)
}

export function buildConfig(
  printer: string,
  filament: string,
  preset: string,
  overrides: Partial<OrcaConfig> = {},
): OrcaConfig {
  const sources = [
    PRINTER_PRESETS[printer],
    FILAMENT_PRESETS[filament],
    PRESETS.find((p) => p.name === preset)?.config ?? {},
    overrides,
  ]
  // A plain {...a, ...b} spread would let a later source's _passthrough
  // wholesale replace an earlier one's instead of merging them — e.g. the
  // quality preset's _passthrough (its own unmapped fields) would silently
  // discard the printer preset's machine_start_gcode/machine_end_gcode.
  // Merge _passthrough across all sources field-by-field instead.
  const merged: OrcaConfig = {}
  let passthrough: Record<string, string> | undefined
  for (const source of sources) {
    const { _passthrough, ...rest } = source
    Object.assign(merged, rest)
    if (_passthrough) passthrough = { ...passthrough, ..._passthrough }
  }
  if (passthrough) merged._passthrough = passthrough
  return merged
}

/**
 * The four corners of a rectangular bed, in the "XxY" vertex format
 * OrcaSlicer's `printable_area` uses and parsePrintableArea() reads back.
 * Shared by toEngineConfig() (which joins them into the flat comma-separated
 * string the engine's set_deserialize_strict expects) and
 * exportOrcaProfileJson() (which writes the JSON array form real profiles
 * use), so the two can't disagree about the winding or the origin corner.
 */
function bedCorners(x: number, y: number): string[] {
  return ['0x0', `${x}x0`, `${x}x${y}`, `0x${y}`]
}

/**
 * The name of the desktop OrcaSlicer printer preset this config corresponds
 * to, following OrcaSlicer's own machine-preset naming convention
 * "<printer model> <nozzle diameter> nozzle" (e.g. "Bambu Lab P1S 0.4
 * nozzle" — verified against the profiles shipped inside OrcaSlicer 2.4.2).
 *
 * Needed because a process/filament preset OrcaSlicer will actually accept
 * must name the printers it applies to in `compatible_printers`: without it
 * the preset is rejected outright ("process not compatible with printer",
 * CLI exit -17), and an empty list does not mean "any printer". Verified by
 * slicing with the exported files against a stock OrcaSlicer install.
 *
 * A guess, necessarily — this app never sees the user's actual preset list,
 * and a vendor whose presets don't follow the convention won't match. That
 * only costs the user editing one field in a plain-text JSON, whereas
 * omitting the key makes the export unusable for everyone.
 */
function printerPresetName(config: OrcaConfig): string | undefined {
  if (config.printer_model === undefined || config.nozzle_diameter === undefined) return undefined
  return `${config.printer_model} ${config.nozzle_diameter} nozzle`
}

/**
 * Translate OrcaConfig field names to the literal OrcaSlicer config option
 * names the WASM bridge expects, for the fields where they differ.
 *
 * The bridge sends every key straight through to
 * `g_config.set_deserialize_strict(key, value)` (orca-wasm/bridge/slicer.cpp)
 * with no key translation of its own — an unrecognized key is silently
 * skipped. `default_speed` and `enable_ironing` are OrcaConfig-only names
 * with no matching real option (verified against PrintConfig.cpp), so
 * everywhere they were previously set — every PRESETS entry (Draft/Standard/
 * Fine) and any imported 3MF with ironing — silently had no effect on the
 * actual slice.
 *
 * Call this once, right before JSON.stringify'ing the config for orc_init.
 */
export function toEngineConfig(config: OrcaConfig): Record<string, unknown> {
  const { default_speed, enable_ironing, bed_temperature, ...rest } = config as OrcaConfig & Record<string, unknown>
  const out: Record<string, unknown> = { ...rest }
  if (config.bed_size_x !== undefined && config.bed_size_y !== undefined) {
    out.printable_area = bedCorners(config.bed_size_x, config.bed_size_y).join(',')
  }
  if (bed_temperature !== undefined) {
    // OrcaSlicer/BambuStudio's real option names — "bed_temperature" isn't
    // in its PrintConfig schema, so set_deserialize_strict silently dropped
    // it and every slice used the engine's own baked-in default instead of
    // the UI value (confirmed: exported .3mf always had hot_plate_temp=45
    // regardless of this field, for every printer preset).
    out.hot_plate_temp = bed_temperature
    out.hot_plate_temp_initial_layer = bed_temperature
  }
  if (default_speed !== undefined) {
    // "Speed of inner wall" (PrintConfig.cpp) — the closest real equivalent
    // to a general/default print speed; OrcaSlicer has no single knob that
    // also scales infill/support speeds, those remain independently set.
    out.inner_wall_speed = default_speed
  }
  if (enable_ironing !== undefined) {
    out.ironing_type = enable_ironing ? 'top' : 'no ironing'
  }
  return out
}

// Which real OrcaSlicer profile file a field belongs to — desktop OrcaSlicer
// profiles are split into separate print/filament/printer presets, each only
// populated with its own option set (see exportOrcaProfileBundle below).
type FieldCategory = 'process' | 'filament' | 'machine'

// OrcaSlicer profile field → OrcaConfig key mapping.
// OrcaSlicer often encodes numbers as strings (e.g. "0.2") and percentages as
// "15%". 'ironing' is its own type (see enable_ironing/ironing_type below):
// unlike bool, its true/false <-> string mapping isn't "1"/"0", it's the
// IroningType enum (s_keys_map_IroningType in PrintConfig.cpp).
//
// `importOnly` marks a field name that must never be written back out by
// exportOrcaProfileJson(). Two kinds qualify, and both have already shipped
// as export bugs once:
//   - Aliases: an alternative real OrcaSlicer/PrusaSlicer spelling of a field
//     whose canonical name is another entry here (e.g. `perimeters` for
//     `wall_loops`). Accepted on import, but exporting the alias instead of
//     the canonical name is at best noise.
//   - Synthetic OrcaConfig-only names with no matching real PrintConfig
//     option at all (`default_speed`, `bed_temperature`, `bed_shape`). These
//     are the dangerous ones: desktop OrcaSlicer silently drops unrecognized
//     keys, so exporting one loses the user's setting with no error.
// Flagging them explicitly (rather than relying on declaration order, which
// is how `default_speed`/`enable_ironing`/`bed_temperature` each leaked into
// exports in the first place) makes REVERSE_FIELD_MAP below order-independent.
const ORCA_FIELD_MAP: Record<
  string,
  {
    key: keyof OrcaConfig
    type: 'num' | 'pct' | 'bool' | 'str' | 'ironing'
    category: FieldCategory
    importOnly?: true
  }
> = {
  layer_height: { key: 'layer_height', type: 'num', category: 'process' },
  // The real FFF field is initial_layer_print_height — initial_layer_height
  // (no "print_") is a distinct SLA-only option (PrintConfigDef::init_sla_params)
  // that set_deserialize_strict on our FFF-only build silently ignores. See
  // OrcaConfig.initial_layer_print_height's own doc comment.
  initial_layer_print_height: { key: 'initial_layer_print_height', type: 'num', category: 'process' },
  wall_loops: { key: 'wall_loops', type: 'num', category: 'process' },
  perimeters: { key: 'wall_loops', type: 'num', category: 'process', importOnly: true }, // alias
  wall_generator: { key: 'wall_generator', type: 'str', category: 'process' },
  top_shell_layers: { key: 'top_shell_layers', type: 'num', category: 'process' },
  bottom_shell_layers: { key: 'bottom_shell_layers', type: 'num', category: 'process' },
  sparse_infill_density: { key: 'sparse_infill_density', type: 'pct', category: 'process' },
  fill_density: { key: 'sparse_infill_density', type: 'pct', category: 'process', importOnly: true }, // alias
  sparse_infill_pattern: { key: 'sparse_infill_pattern', type: 'str', category: 'process' },
  fill_pattern: { key: 'sparse_infill_pattern', type: 'str', category: 'process', importOnly: true }, // alias
  outer_wall_speed: { key: 'outer_wall_speed', type: 'num', category: 'process' },
  external_perimeter_speed: { key: 'outer_wall_speed', type: 'num', category: 'process', importOnly: true }, // alias
  // inner_wall_speed is the real OrcaSlicer field; `default_speed` is an
  // OrcaConfig-only synthetic name (see toEngineConfig's doc comment) kept
  // readable on import so profiles this app exported before the fix still
  // load, but never written back out.
  inner_wall_speed: { key: 'default_speed', type: 'num', category: 'process' },
  default_speed: { key: 'default_speed', type: 'num', category: 'process', importOnly: true },
  travel_speed: { key: 'travel_speed', type: 'num', category: 'process' },
  initial_layer_speed: { key: 'initial_layer_speed', type: 'num', category: 'process' },
  first_layer_speed: { key: 'initial_layer_speed', type: 'num', category: 'process', importOnly: true }, // alias
  brim_width: { key: 'brim_width', type: 'num', category: 'process' },
  brim_type: { key: 'brim_type', type: 'str', category: 'process' },
  skirt_loops: { key: 'skirt_loops', type: 'num', category: 'process' },
  skirt_distance: { key: 'skirt_distance', type: 'num', category: 'process' },
  raft_layers: { key: 'raft_layers', type: 'num', category: 'process' },
  seam_position: { key: 'seam_position', type: 'str', category: 'process' },
  enable_support: { key: 'enable_support', type: 'bool', category: 'process' },
  support_type: { key: 'support_type', type: 'str', category: 'process' },
  // ironing_type is the real OrcaSlicer field (s_keys_map_IroningType: "no
  // ironing"/"top"/"topmost"/"solid") — there is no real "ironing" or
  // "enable_ironing" option (verified against PrintConfig.cpp). enable_ironing
  // is an OrcaConfig-only simplified boolean toggle for the UI; the 'ironing'
  // type below is what translates it to/from the real enum string, mirroring
  // toEngineConfig's own enable_ironing -> ironing_type conversion.
  ironing_type: { key: 'enable_ironing', type: 'ironing', category: 'process' },
  fuzzy_skin: { key: 'fuzzy_skin', type: 'str', category: 'process' },
  fuzzy_skin_thickness: { key: 'fuzzy_skin_thickness', type: 'num', category: 'process' },
  fuzzy_skin_point_dist: { key: 'fuzzy_skin_point_dist', type: 'num', category: 'process' },
  // filament fields
  filament_type: { key: 'filament_type', type: 'str', category: 'filament' },
  nozzle_temperature: { key: 'nozzle_temperature', type: 'num', category: 'filament' },
  temperature: { key: 'nozzle_temperature', type: 'num', category: 'filament', importOnly: true }, // alias
  // hot_plate_temp is the real OrcaSlicer field — "bed_temperature" is not in
  // its PrintConfig schema at all, so exporting it silently loses the user's
  // bed temperature on import into desktop OrcaSlicer (the same failure mode
  // toEngineConfig documents for the engine side).
  hot_plate_temp: { key: 'bed_temperature', type: 'num', category: 'filament' },
  bed_temperature: { key: 'bed_temperature', type: 'num', category: 'filament', importOnly: true },
  fan_min_speed: { key: 'fan_min_speed', type: 'num', category: 'filament' },
  // machine fields
  printer_model: { key: 'printer_model', type: 'str', category: 'machine' },
  nozzle_diameter: { key: 'nozzle_diameter', type: 'num', category: 'machine' },
  printable_height: { key: 'printable_height', type: 'num', category: 'machine' },
  max_print_height: { key: 'printable_height', type: 'num', category: 'machine', importOnly: true }, // alias
  // OrcaConfig-only: real OrcaSlicer machine profiles describe bed geometry
  // solely through printable_area (parseOrcaProfileJson derives circle-ness
  // from its vertex count), and "rectangle"/"circle" aren't valid values for
  // any polygon field — so this is never written back out.
  bed_shape: { key: 'bed_shape', type: 'str', category: 'machine', importOnly: true },
  // bed size — handled separately via parsePrintableArea() below
}

/**
 * Detects an OrcaSlicer machine profile describing more than one physical
 * extruder/nozzle (e.g. Bambu Lab H2D), which our WASM build cannot support
 * — it's hard-coded single-extruder, so it never has the per-extruder array
 * lengths (nozzle_diameter, extruder_variant_list, and everything gated
 * behind DynamicPrintConfig::support_different_extruders(), PrintConfig.cpp:8966-8987
 * in orca-wasm/orca/src/libslic3r/) that a real multi-extruder profile's
 * full field set — including G-code fields that reference per-extruder-
 * indexed placeholders like `[previous_extruder]` — expects.
 * Passing that field set through via _passthrough crashes Print::apply()
 * with a WASM "memory access out of bounds" trap (confirmed against the
 * real Bambu Lab H2D profile; not caught by any single field-level denylist
 * since the crash involves dozens of ordinary fields interacting through
 * G-code placeholder evaluation, not just the multi-extruder-specific ones).
 * Mirrors support_different_extruders()'s own two conditions exactly, so any
 * profile that would flip the engine into "different extruders" mode has
 * its passthrough dropped entirely rather than risk it.
 *
 * Real OrcaSlicer profile JSON always represents multi-value fields as JSON
 * arrays (e.g. `["0.4","0.4"]`), never a flattened comma/semicolon string —
 * verified directly against the actual downloaded BBL profiles. The
 * fallback below is defensive for hand-edited/non-standard input, matching
 * how parsePrintableArea() below already falls back to string-splitting.
 */
function isMultiExtruderProfile(raw: Record<string, unknown>): boolean {
  function hasMultipleEntries(val: unknown): boolean {
    if (val === undefined || val === null) return false
    // extruder_variant_list's real shape is an array with one entry per
    // physical extruder, where each entry is itself a comma-joined list of
    // that extruder's supported variants (e.g. a single-extruder X1C profile
    // has extruder_variant_list: ["Direct Drive Standard,Direct Drive High Flow"]
    // — 1 array element, but 2 variants, which is enough to flip
    // support_different_extruders() to true). Splitting every element by
    // ","/";" before counting catches that case as well as the "flattened
    // to one big string" defensive fallback for non-array input.
    const rawEntries = Array.isArray(val) ? val.map(String) : [String(val)]
    const entries = rawEntries.flatMap((entry) =>
      entry
        .split(/[,;]/)
        .map((s) => s.trim())
        .filter(Boolean),
    )
    return entries.length > 1
  }

  return hasMultipleEntries(raw.nozzle_diameter) || hasMultipleEntries(raw.extruder_variant_list)
}

/**
 * Parse bed size from OrcaSlicer's `printable_area` field.
 *
 * OrcaSlicer stores bed corners as an array of "XxY" strings, e.g.:
 *   ["0x0", "256x0", "256x256", "0x256"]
 * or as a flat comma-joined string: "0x0,256x0,256x256,0x256"
 *
 * Returns { dims: [maxX, maxY], circle: boolean } or null if unparseable.
 * When the polygon has more than 8 points it's treated as a circular bed.
 */
function parsePrintableArea(raw: unknown): { dims: [number, number]; circle: boolean } | null {
  let pts: string[]
  if (Array.isArray(raw)) {
    pts = raw.map(String)
  } else {
    const s = String(raw).trim()
    if (!s) return null
    pts = s.split(',')
  }
  let minX = Infinity,
    maxX = -Infinity,
    minY = Infinity,
    maxY = -Infinity
  let pointCount = 0
  for (const pt of pts) {
    const parts = pt.trim().split('x')
    if (parts.length < 2) continue
    const x = parseFloat(parts[0]),
      y = parseFloat(parts[1])
    if (!Number.isNaN(x) && !Number.isNaN(y)) {
      minX = Math.min(minX, x)
      maxX = Math.max(maxX, x)
      minY = Math.min(minY, y)
      maxY = Math.max(maxY, y)
      pointCount++
    }
  }
  // Bed size is the bounding-box extent. For corner-origin rectangular beds the
  // origin is (0,0) so this equals maxX/maxY; for center-origin circular/delta
  // beds (coords −r..+r) this gives the full diameter, not the radius.
  const sizeX = maxX - minX,
    sizeY = maxY - minY
  if (!(sizeX > 0) || !(sizeY > 0)) return null
  // Circular beds are approximated as polygons with many vertices in OrcaSlicer profiles.
  return { dims: [sizeX, sizeY], circle: pointCount > 8 }
}

export function parseOrcaProfileJson(json: string): Partial<OrcaConfig> {
  try {
    const raw = JSON.parse(json) as Record<string, unknown>

    // Support array-wrapped values (OrcaSlicer wraps some fields: ["0.2"])
    function unwrap(v: unknown): unknown {
      return Array.isArray(v) && v.length === 1 ? v[0] : v
    }

    const config: Partial<OrcaConfig> = {}

    for (const [field, meta] of Object.entries(ORCA_FIELD_MAP)) {
      if (!(field in raw)) continue
      const raw_val = unwrap(raw[field])
      // meta.key's associated OrcaConfig property type varies per field (number/boolean/string)
      // depending on meta.type, which TS can't correlate — widen to unknown so writes below
      // type-check without an `any` escape hatch.
      const out = config as Record<keyof OrcaConfig, unknown>
      if (meta.type === 'num') {
        const n = parseFloat(String(raw_val))
        if (!Number.isNaN(n)) out[meta.key] = n
      } else if (meta.type === 'pct') {
        // "15%" → 15, "0.15" → 15, "15" → 15 (OrcaSlicer integer), "1" → 1 (not 100)
        const s = String(raw_val).trim()
        const parsed = parseFloat(s)
        const n = s.endsWith('%') ? parsed : parsed < 1 ? parsed * 100 : parsed
        if (!Number.isNaN(n)) out[meta.key] = Math.round(n)
      } else if (meta.type === 'bool') {
        const s = String(raw_val).toLowerCase()
        out[meta.key] = s === '1' || s === 'true' || s === 'yes'
      } else if (meta.type === 'ironing') {
        // s_keys_map_IroningType: "no ironing"/"top"/"topmost"/"solid" — any
        // non-empty value other than "no ironing" means ironing is enabled.
        const s = String(raw_val).trim().toLowerCase()
        out[meta.key] = s !== '' && s !== 'no ironing'
      } else {
        out[meta.key] = String(raw_val)
      }
    }

    // ── Bed size ─────────────────────────────────────────────────────────────
    // OrcaSlicer machine profiles carry printable_area / bed_size for bed dims.
    if ('printable_area' in raw) {
      const result = parsePrintableArea(raw.printable_area)
      if (result) {
        config.bed_size_x = result.dims[0]
        config.bed_size_y = result.dims[1]
        if (result.circle && !config.bed_shape) config.bed_shape = 'circle'
      }
    } else if ('bed_size' in raw) {
      // Some older profiles use bed_size: ["256", "256"] or "256x256"
      const bs = unwrap(raw.bed_size)
      if (Array.isArray(bs) && bs.length >= 2) {
        const x = parseFloat(String(bs[0])),
          y = parseFloat(String(bs[1]))
        if (!Number.isNaN(x) && x > 0) config.bed_size_x = x
        if (!Number.isNaN(y) && y > 0) config.bed_size_y = y
      } else {
        const result = parsePrintableArea(bs)
        if (result) {
          config.bed_size_x = result.dims[0]
          config.bed_size_y = result.dims[1]
          if (result.circle && !config.bed_shape) config.bed_shape = 'circle'
        }
      }
    }

    // ── Passthrough for unmapped OrcaSlicer fields ───────────────────────────
    // Collect every field not already processed so it can be forwarded verbatim
    // to the WASM slicer (which accepts any DynamicPrintConfig key) — except
    // for genuinely multi-extruder machine profiles, whose full field set
    // crashes our single-extruder WASM build (see isMultiExtruderProfile).
    if (!isMultiExtruderProfile(raw)) {
      const SKIP_META = new Set([
        'type',
        'name',
        'inherits',
        'from',
        'version',
        'description',
        '__proto__',
        'constructor',
        'prototype',
      ])
      // Keep printable_area verbatim so non-rectangular and offset beds survive
      // import -> export. toEngineConfig supplies a rectangular fallback for
      // built-in presets, while this passthrough value takes precedence later.
      const SKIP_BED = new Set(['bed_size'])
      const alreadyMapped = new Set(Object.keys(ORCA_FIELD_MAP))
      const passthrough: Record<string, string> = Object.create(null) as Record<string, string>
      for (const [field, val] of Object.entries(raw)) {
        if (SKIP_META.has(field) || SKIP_BED.has(field) || alreadyMapped.has(field)) continue
        if (val === null || val === undefined) continue
        let sv: string
        if (Array.isArray(val)) {
          // OrcaSlicer wraps values in arrays (single-extruder: ["0.8"], multi: ["0.8","1.0"]).
          // OrcaSlicer's config deserializer expects multi-value options as comma-separated strings.
          sv = val
            .filter((x) => x !== null && x !== undefined)
            .map((x) => (typeof x === 'boolean' ? (x ? '1' : '0') : String(x)))
            .join(',')
        } else {
          sv = typeof val === 'boolean' ? (val ? '1' : '0') : String(val)
        }
        if (sv !== '') passthrough[field] = sv
      }
      if (Object.keys(passthrough).length > 0) config._passthrough = passthrough
    }

    return config
  } catch {
    return {}
  }
}

// Reverse of ORCA_FIELD_MAP: for each internal OrcaConfig key, the real
// OrcaSlicer field name to write on export. Built by skipping every
// `importOnly` entry rather than by taking the first field seen for a key —
// declaration order is not a safe signal here, and relying on it is exactly
// how default_speed, enable_ironing and bed_temperature each shipped as the
// exported name for a field OrcaSlicer doesn't have. A key whose only entry
// is importOnly (e.g. bed_shape) is deliberately absent, and so never
// exported at all.
const REVERSE_FIELD_MAP: Partial<Record<keyof OrcaConfig, string>> = {}
for (const [field, meta] of Object.entries(ORCA_FIELD_MAP)) {
  if (meta.importOnly) continue
  if (meta.key in REVERSE_FIELD_MAP) {
    throw new Error(
      `ORCA_FIELD_MAP: "${field}" and "${REVERSE_FIELD_MAP[meta.key]}" both claim to be the exported name for ` +
        `"${meta.key}" — exactly one entry per key may omit importOnly.`,
    )
  }
  REVERSE_FIELD_MAP[meta.key] = field
}

/**
 * Serialize the current in-app config back into a single OrcaSlicer-
 * compatible profile JSON of one type (`process`/`filament`/`machine`) — the
 * mirror of parseOrcaProfileJson(). Only fields belonging to `category` are
 * written (canonical OrcaSlicer field names via REVERSE_FIELD_MAP), matching
 * how real OrcaSlicer print/filament/printer presets are three genuinely
 * separate option sets, not one flat file — a "process" preset with e.g.
 * nozzle_diameter (a machine-only option) mixed in isn't a shape desktop
 * OrcaSlicer's preset bundles ever produce themselves. Percentages are
 * written as "NN%" and printable_area as bed-corner strings, so each file is
 * also loadable by desktop OrcaSlicer as a user preset of that type.
 *
 * `_passthrough` fields can't be reliably attributed to a single category —
 * they arrive pre-merged from potentially multiple sources (buildConfig
 * merges every preset layer's _passthrough together; parseOrcaProfileJson
 * dumps every unmapped field from whichever single file was imported into
 * one bag) — so they're written to every category's file rather than
 * risking silently dropping one. A passthrough field that doesn't belong to
 * a given file's category is simply an unrecognized key there, same as any
 * other key set_deserialize_strict doesn't know.
 *
 * Exported by exportOrcaProfileBundle() below for actual use; kept as its
 * own function (rather than inlined) so tests can assert one category's
 * output directly.
 */
export function exportOrcaProfileJson(config: OrcaConfig, name: string, category: FieldCategory): string {
  const { _passthrough, bed_size_x, bed_size_y, ...rest } = config
  const out: Record<string, unknown> = {
    type: category,
    name,
    from: 'User',
  }
  for (const [orcaKey, value] of Object.entries(rest)) {
    if (value === undefined || value === null) continue
    const field = REVERSE_FIELD_MAP[orcaKey as keyof OrcaConfig]
    if (!field) continue
    const meta = ORCA_FIELD_MAP[field]
    if (meta.category !== category) continue
    out[field] =
      meta.type === 'pct'
        ? `${value}%`
        : meta.type === 'ironing'
          ? value
            ? 'top'
            : 'no ironing'
          : typeof value === 'boolean'
            ? value
              ? '1'
              : '0'
            : String(value)
  }
  if (category === 'filament' && config.bed_temperature !== undefined) {
    // OrcaSlicer splits bed temperature into the steady-state and first-layer
    // options; the UI has one knob, so both get it — mirroring exactly what
    // toEngineConfig() sends to the engine, so an exported profile slices the
    // same way in desktop OrcaSlicer as it did here.
    out.hot_plate_temp_initial_layer = String(config.bed_temperature)
  }
  if (category === 'process' || category === 'filament') {
    // Without this the preset is rejected on load — see printerPresetName().
    const printer = printerPresetName(config)
    if (printer) out.compatible_printers = [printer]
  }
  if (category === 'machine' && bed_size_x !== undefined && bed_size_y !== undefined) {
    out.printable_area = bedCorners(bed_size_x, bed_size_y)
  }
  if (_passthrough) Object.assign(out, _passthrough)
  return JSON.stringify(out, null, 2)
}

/**
 * Export the current settings as a full OrcaSlicer preset bundle — one file
 * per real preset type (process/filament/machine), matching how desktop
 * OrcaSlicer itself stores and imports presets (see exportOrcaProfileJson's
 * own doc comment for why a single flat file can't represent this). Used by
 * SettingsPanel's "Export" button, which zips the three files together so
 * the whole bundle downloads as one action.
 */
export function exportOrcaProfileBundle(
  config: OrcaConfig,
  baseName: string,
): { filename: string; category: FieldCategory; json: string }[] {
  return (['process', 'filament', 'machine'] as const).map((category) => ({
    filename: `${category}.json`,
    category,
    json: exportOrcaProfileJson(config, `${baseName} (${category})`, category),
  }))
}
