import orcaProfiles from '../data/orca-profiles.json'
import type { OrcaConfig, PassthroughConfig, SlicePreset } from '../types'

// orcaProfiles is generated by scripts/fetch-orca-profiles.ts from
// OrcaSlicer's own bundled profile tree (resources/profiles/<Vendor>/...),
// resolving each profile's `inherits` chain. Re-fetch with:
//   npx tsx scripts/fetch-orca-profiles.ts
export const PRESETS: SlicePreset[] = orcaProfiles.qualityPresets as SlicePreset[]

export const FILAMENT_PRESETS: Record<string, Partial<OrcaConfig>> = orcaProfiles.filamentPresets

// bed_size_x/y and printable_height are real values from OrcaSlicer's own
// bundled profiles (resources/profiles/<Vendor>/machine/*.json) — our
// headless WASM build ships none of these, so the web UI's presets are the
// only source of truth for them. printable_height in particular used to be
// missing entirely, silently falling back to the *engine's* generic
// FullPrintConfig default of 100mm (PrintConfig.cpp) — well under any of
// these printers' real Z height, so any model taller than 100mm failed
// "exceeds the maximum build volume height" validation regardless of which
// printer was selected.
export const PRINTER_PRESETS: Record<string, Partial<OrcaConfig>> = orcaProfiles.printerPresets

// UI display fallbacks for config fields a preset may leave unset. Display
// only — deliberately NOT merged into the engine config (an unset field must
// keep falling back to the engine's own default, which may differ). Having
// one table keeps every surface (settings inputs, config summary, 3D bed
// viewers) quoting the same number instead of each hardcoding its own.
//
// For every field the engine also has, the value here MUST equal that
// engine default (PrintConfig.cpp's set_default_value), and new entries
// should be checked against it. Not cosmetic: because these are display-only,
// a field left unset is absent from exportOrcaProfileJson()'s output too —
// desktop OrcaSlicer then resolves it from the same engine default, so an
// entry that disagrees means the panel shows one number while both the local
// slice and the exported preset silently use another. wall_loops sat at 3
// against the engine's 2 for exactly that reason.
export const DISPLAY_DEFAULTS = {
  printer_model: 'Generic',
  nozzle_diameter: 0.4,
  bed_size_x: 256,
  bed_size_y: 256,
  bed_shape: 'rectangle',
  filament_type: 'PLA',
  nozzle_temperature: 220,
  bed_temperature: 60,
  layer_height: 0.2,
  initial_layer_print_height: 0.2,
  top_shell_layers: 4,
  bottom_shell_layers: 3,
  wall_loops: 2,
  wall_generator: 'arachne',
  sparse_infill_density: 15,
  sparse_infill_pattern: 'grid',
  default_speed: 100,
  outer_wall_speed: 60,
  initial_layer_speed: 30,
  travel_speed: 150,
  seam_position: 'aligned',
  fuzzy_skin: 'none',
  fuzzy_skin_thickness: 0.3,
  fuzzy_skin_point_dist: 0.8,
  enable_support: false,
  support_type: 'normal(auto)',
  brim_width: 0,
  brim_type: 'auto_brim',
  skirt_loops: 1,
  skirt_distance: 2,
  raft_layers: 0,
} as const satisfies OrcaConfig

/**
 * Split the config's filament_type into the individual material names it
 * mentions, for display only (ConfigSummary's "Material" row) — an imported
 * profile can carry something like "PLA;PETG" and listing both reads better
 * than printing the raw string.
 *
 * Explicitly NOT a slot count. It's tempting to read one entry here as one
 * AMS slot, and an earlier revision of this file claimed exactly that, but
 * it is false: measured against OrcaSlicer 2.4.2, "PLA;PETG" resolves to a
 * single filament (`['PLA']`), "PLA,PETG" to `['PLA,PETG']`, and even a JSON
 * array `["PLA","PETG"]` to `['PLA']`. The engine's filament count is the
 * number of separate filament *presets* it was given, which this app does
 * not model — see issue #155 before using this for anything but text.
 */
export function filamentSlots(config: OrcaConfig): string[] {
  return String(config.filament_type ?? DISPLAY_DEFAULTS.filament_type)
    .split(/[;,]/)
    .map((entry) => entry.trim())
    .filter(Boolean)
}

/**
 * Default slot colours. `filament_colour` is not cosmetic here: the engine
 * derives its filament *count* from `filament_colour.values.size()`
 * (ToolOrdering.cpp's `number_of_extruders`), which then sizes the flush
 * matrix. A slot without a colour is a slot the engine does not know exists.
 */
const SLOT_COLOURS = ['#F5A623', '#4A90D9', '#7ED321', '#D0021B', '#9013FE', '#50E3C2', '#F8E71C', '#B8E986']

/**
 * Upper bound on filament slots offered in the UI — one per SLOT_COLOURS entry,
 * comfortably above the 4 slots of a single AMS unit. The engine imposes no
 * limit of its own, but each extra slot grows the flush matrix quadratically.
 */
export const MAX_FILAMENT_SLOTS = SLOT_COLOURS.length

/** Volume purged when switching between two different filaments, in mm³. */
const FLUSH_VOLUME = 280

/**
 * Filament diameter for a slot nothing declares one for, in mm — the engine's
 * own PrintConfig.cpp default, and what every FFF profile this app ships is
 * built around. Only a fallback: an imported profile carrying 2.85 keeps it.
 */
const DEFAULT_FILAMENT_DIAMETER = '1.75'

/**
 * How many physical nozzles the chosen printer has. Real multi-nozzle machines
 * carry a `nozzle_diameter` array (a Bambu Lab H2D has two); everything else
 * is a single nozzle feeding however many filament slots.
 */
function nozzleCount(config: Partial<OrcaConfig> | undefined): number {
  const raw = config?._passthrough?.nozzle_diameter
  return Array.isArray(raw) && raw.length > 0 ? raw.length : 1
}

/**
 * The per-filament options the engine needs in order to treat a config as
 * having N filaments rather than one.
 *
 * Every filament-indexed vector has to be N long, because the engine indexes
 * them by filament id; a short one is read out of bounds. The three that are
 * easy to miss:
 *
 *  - `filament_colour` defines the count (see SLOT_COLOURS).
 *  - `flush_volumes_matrix` holds one N×N sub-matrix *per nozzle*, laid out
 *    end to end — `get_flush_volumes_matrix()` slices it by nozzle id.
 *  - `flush_multiplier` has one entry per nozzle, and is what
 *    `GCode::append_full_config()` divides the matrix length by to check it
 *    ("Flush volumes matrix do not match to the correct size!").
 *
 * `filament_map` assigns each slot to a physical extruder (1-based). Slots are
 * spread round-robin over the available nozzles, so a single-nozzle AMS-style
 * printer maps every slot to extruder 1, while a dual-nozzle machine alternates
 * — which is what produces genuine T0/T1 tool changes.
 *
 * Everything here only *fills in* what the config does not already say. An
 * imported multi-material profile brings its own colours, diameters, per-slot
 * temperatures and flush matrix, and those are the user's values: `_passthrough`
 * is spread over the resolved config, so regenerating them from a stock preset
 * would silently replace what was imported. See `per()` for the priority order.
 */
export function withFilamentSlots(config: OrcaConfig, filaments: string[]): OrcaConfig {
  const ui = filaments.filter((name) => name in FILAMENT_PRESETS)
  // An imported profile can declare more filaments than the UI has slots for
  // (a multi-material project file). The queue's picker offers those slots
  // too — it reads the same count — so they need the same per-filament
  // vectors; sizing only the UI's slots is exactly what leaves the engine
  // indexing past the end of one.
  const n = Math.max(ui.length, declaredSlotCount(config))
  // One slot is the pre-existing single-filament config, untouched.
  if (n < 2) return config
  // Nozzle count is deliberately resolved from the *merged* config rather than
  // the built-in printer preset: an imported machine profile (a real
  // dual-nozzle H2D) only shows up once the layers are combined, and it is
  // what decides whether the slots land on one nozzle or alternate across two.
  const extra = multiFilamentPassthrough(config, ui, n, nozzleCount(config))
  return { ...config, _passthrough: { ...config._passthrough, ...extra } }
}

/**
 * How many filaments the config already declares on its own, ignoring the UI's
 * slot list — `filament_colour` is the engine's count, and `filament_type` is
 * the multi-value form a multi-material profile arrives in.
 */
function declaredSlotCount(config: OrcaConfig): number {
  const pt = config._passthrough
  if (Array.isArray(pt?.filament_colour)) return pt.filament_colour.length
  return Array.isArray(pt?.filament_type) ? pt.filament_type.length : 1
}

/**
 * Where slot `i` takes its per-filament values from.
 *
 * Slot 0 is the slot the settings panel edits, so it reads the *resolved*
 * config — manual overrides and any imported filament layer included — not the
 * stock preset for its material. These arrays land in `_passthrough`, which
 * the worker spreads *over* the resolved config, so reading the preset here is
 * what used to make adding a second slot silently revert a hand-typed nozzle
 * or bed temperature back to the preset value.
 *
 * Slots the UI knows about take their stock preset. Slots beyond it exist only
 * because an imported profile declared them, so they take whatever it named.
 *
 * `filament_type` is the one field slot 0 cannot read straight off the resolved
 * config: ORCA_FIELD_MAP collapses a multi-value option to a single scalar for
 * display, so an imported multi-material profile leaves `config.filament_type`
 * as the joined "PLA,PETG" rather than this slot's own type. The unflattened
 * array is still in the passthrough, so take slot 0's entry from there.
 */
function slotSource(config: OrcaConfig, ui: string[], i: number): Partial<OrcaConfig> {
  const declared = config._passthrough?.filament_type
  const perSlot = Array.isArray(declared) ? declared : undefined
  if (i === 0) return perSlot?.[0] ? { ...config, filament_type: perSlot[0] } : config
  if (i < ui.length) return FILAMENT_PRESETS[ui[i]] ?? {}
  const type = perSlot?.[i]
  if (!type) return {}
  return FILAMENT_PRESETS[type] ?? { filament_type: type }
}

/**
 * Options the settings panel edits, and therefore the ones whose slot 0 has to
 * come from the *resolved* config rather than from whatever the imported layer
 * declared — a manual override lives in the resolved config, and `_passthrough`
 * is spread over it, so preferring the declared value here would silently
 * revert the user's edit (the #159 interaction). Every other per-filament
 * option has no UI of its own, so a declared value is the best answer for any
 * slot including the first.
 *
 * "Edits" means whatever toEngineConfig() writes from a panel field, not just
 * the fields the panel names. Its one "Bed temp" knob fans out to *both*
 * hot_plate_temp and hot_plate_temp_initial_layer, so both belong here — with
 * only the first listed, a single-slot config put the typed value in both
 * while a multi-slot one silently left the first layer on the imported
 * profile's temperature. `nozzle_temperature_initial_layer` is deliberately
 * absent for exactly the same reason read the other way: toEngineConfig()
 * never writes it, so there is no panel value for a declared one to contradict.
 */
const PANEL_EDITED_SLOT_OPTIONS = new Set([
  'filament_type',
  'nozzle_temperature',
  'hot_plate_temp',
  'hot_plate_temp_initial_layer',
])

/**
 * Colour for a slot the config did not name one for. Past the hand-picked
 * palette (only reachable when an imported profile declares more slots than
 * the UI offers) walk the hue circle by the golden angle instead of repeating
 * it, so the extra slots stay visually distinct from each other.
 */
function slotColour(i: number): string {
  if (i < SLOT_COLOURS.length) return SLOT_COLOURS[i]
  const hue = ((i * 137.508) % 360) / 360
  // Standard HSL -> RGB (the hue2rgb helper), at a saturation and lightness
  // picked to sit alongside SLOT_COLOURS rather than for any property of their
  // own. Derived from those two rather than written out as literals: the ramp's
  // slope is a function of the min/max it moves between, and an earlier
  // revision had them disagree by a factor of two — leaving the piecewise curve
  // discontinuous at both joins, so some hues came out muddy while this comment
  // still claimed a plain HSL conversion.
  const saturation = 0.62
  const lightness = 0.55
  const chroma = (1 - Math.abs(2 * lightness - 1)) * saturation
  const min = lightness - chroma / 2
  const max = lightness + chroma / 2
  const slope = 6 * chroma
  const channel = (offset: number): string => {
    const t = (hue + offset) % 1
    const v = t < 1 / 6 ? min + slope * t : t < 1 / 2 ? max : t < 2 / 3 ? max - slope * (t - 1 / 2) : min
    return Math.round(v * 255)
      .toString(16)
      .padStart(2, '0')
  }
  return `#${channel(1 / 3)}${channel(0)}${channel(2 / 3)}`
}

function multiFilamentPassthrough(config: OrcaConfig, ui: string[], n: number, nozzles: number): PassthroughConfig {
  const sources = Array.from({ length: n }, (_, i) => slotSource(config, ui, i))

  /** Whatever the config already carries for `key`, one entry per slot. */
  const declared = (key: string): (string | undefined)[] => {
    const raw = config._passthrough?.[key]
    if (raw === undefined) return []
    return Array.isArray(raw) ? raw : [raw]
  }

  /**
   * One value per slot for an option with no UI and nothing to derive it from:
   * whatever the config declared for that slot, else `fallback`. Used for the
   * options `per()` below cannot serve because they have no material to read.
   */
  const declaredOr = (key: string, fallback: (i: number) => string): string[] => {
    const values = declared(key)
    return Array.from({ length: n }, (_, i) => values[i] ?? fallback(i))
  }

  /**
   * One value per slot, preferring what the config already declared for that
   * slot over anything derived. An imported multi-material profile is the only
   * thing that can declare these, and its values are the user's — regenerating
   * them from a stock preset is the same silent-revert bug PANEL_EDITED_SLOT_
   * OPTIONS exists to avoid, one slot further down the list.
   *
   * A slot the UI names is the exception: the user picked that material in the
   * panel, so it outranks whatever an older import happened to say.
   *
   * That exception is only sound while `pick` genuinely reads the slot's own
   * material — it is what makes the derived value more current than the
   * declared one. An option with nothing to pick has no such value to offer
   * and would only overwrite the import with `fallback`, so it belongs in
   * `declaredOr()` above instead. `filament_diameter` sat here with `() => undefined`
   * and silently reset an imported 2.85 mm profile's second slot to 1.75.
   */
  const per = (key: string, pick: (src: Partial<OrcaConfig>) => unknown, fallback: string | number): string[] => {
    const own = declared(key)
    const derived = (i: number) => String(pick(sources[i]) ?? fallback)
    return Array.from({ length: n }, (_, i) => {
      if (i === 0) return PANEL_EDITED_SLOT_OPTIONS.has(key) ? derived(0) : (own[0] ?? derived(0))
      if (i < ui.length) return derived(i)
      return own[i] ?? derived(i)
    })
  }

  // Per-filament G-code hooks. The engine reads these with .at(filament_id)
  // (GCode.cpp's filament_start_gcode lookup), so a vector left at its
  // one-entry default throws the moment anything prints with a filament other
  // than the first — which is why assigning an object to slot 2 used to fail
  // while slot 1 worked. Pad whatever the printer or imported profile already
  // set across the new slots rather than blanking it: overwriting with "" is a
  // silent way to drop a preset's own filament start G-code (a K-factor line,
  // say), which a single-slot config would still have honoured.
  const padHook = (key: 'filament_start_gcode' | 'filament_end_gcode'): string[] => {
    const raw = config._passthrough?.[key]
    const existing = raw === undefined ? [] : Array.isArray(raw) ? raw : [raw]
    return Array.from({ length: n }, (_, i) => existing[i] ?? existing[0] ?? '')
  }

  /**
   * A declared vector, but only when it is already exactly the shape this slot
   * count and nozzle count require. Unlike the per-slot options above these
   * cannot be honoured entry by entry: the engine validates their whole length
   * and rejects anything else outright ("Flush volumes matrix do not match to
   * the correct size!"), so one sized for the profile's own filament or nozzle
   * count has to be regenerated rather than padded.
   */
  const declaredIfSized = (key: string, length: number, ok: (v: string) => boolean = () => true) => {
    const own = declared(key)
    if (own.length !== length) return undefined
    return own.every((v) => v !== undefined && ok(v)) ? (own as string[]) : undefined
  }

  // One N×N matrix per nozzle: 0 to purge a filament into itself, FLUSH_VOLUME
  // between two different ones.
  const matrix: string[] = []
  for (let nozzle = 0; nozzle < nozzles; nozzle++)
    for (let from = 0; from < n; from++)
      for (let to = 0; to < n; to++) matrix.push(String(from === to ? 0 : FLUSH_VOLUME))

  // A profile that already assigns its slots to nozzles knows better than
  // round-robin — but only if it names nozzles this machine has. Anything else
  // (a map carried over from a printer with more extruders) would have the
  // engine index one that does not exist.
  const namesANozzle = (v: string) => Number.isInteger(Number(v)) && Number(v) >= 1 && Number(v) <= nozzles

  return {
    filament_type: per('filament_type', (p) => p.filament_type, DISPLAY_DEFAULTS.filament_type),
    filament_colour: declaredOr('filament_colour', slotColour),
    // No FILAMENT_PRESETS entry carries a diameter, so there is nothing a UI
    // slot could derive — declared value first for every slot, 1.75 only where
    // nothing said otherwise. See per()'s doc for why this is not per().
    filament_diameter: declaredOr('filament_diameter', () => DEFAULT_FILAMENT_DIAMETER),
    nozzle_temperature: per('nozzle_temperature', (p) => p.nozzle_temperature, DISPLAY_DEFAULTS.nozzle_temperature),
    nozzle_temperature_initial_layer: per(
      'nozzle_temperature_initial_layer',
      (p) => p.nozzle_temperature,
      DISPLAY_DEFAULTS.nozzle_temperature,
    ),
    hot_plate_temp: per('hot_plate_temp', (p) => p.bed_temperature, DISPLAY_DEFAULTS.bed_temperature),
    hot_plate_temp_initial_layer: per(
      'hot_plate_temp_initial_layer',
      (p) => p.bed_temperature,
      DISPLAY_DEFAULTS.bed_temperature,
    ),
    filament_start_gcode: padHook('filament_start_gcode'),
    filament_end_gcode: padHook('filament_end_gcode'),
    filament_map:
      declaredIfSized('filament_map', n, namesANozzle) ??
      Array.from({ length: n }, (_, i) => String((i % nozzles) + 1)),
    filament_map_mode: 'Manual',
    flush_volumes_matrix: declaredIfSized('flush_volumes_matrix', nozzles * n * n) ?? matrix,
    flush_multiplier: declaredIfSized('flush_multiplier', nozzles) ?? Array.from({ length: nozzles }, () => '1'),
  }
}

/**
 * One label per real filament slot, in engine order — what the queue's
 * per-object picker lists and, via its length, the number of slots anything
 * assigned to a slot may legally name.
 *
 * Reads the same count the engine does (`filament_colour`, else the
 * multi-value `filament_type` an imported multi-material profile arrives in),
 * so it cannot disagree with what withFilamentSlots() actually sized. Falls
 * back to filamentSlots() for a single-slot config, which is display text
 * rather than a count — see its doc and #155.
 */
export function filamentSlotLabels(config: OrcaConfig): string[] {
  const types = config._passthrough?.filament_type
  const perSlot = Array.isArray(types) ? types : undefined
  const count = declaredSlotCount(config)
  if (count < 2) return filamentSlots(config)
  const fallback = String(config.filament_type ?? DISPLAY_DEFAULTS.filament_type)
  return Array.from({ length: count }, (_, i) => perSlot?.[i] || fallback)
}

export function buildConfig(
  printer: string,
  filament: string | string[],
  preset: string,
  overrides: Partial<OrcaConfig> = {},
): OrcaConfig {
  // The first slot drives every scalar the settings panel shows; the rest only
  // exist as the per-filament arrays added below.
  const filaments = (Array.isArray(filament) ? filament : [filament]).filter((name) => name in FILAMENT_PRESETS)
  const slots = filaments.length > 0 ? filaments : ['PLA']
  const sources = [
    PRINTER_PRESETS[printer],
    FILAMENT_PRESETS[slots[0]],
    PRESETS.find((p) => p.name === preset)?.config ?? {},
    overrides,
  ]
  // A plain {...a, ...b} spread would let a later source's _passthrough
  // wholesale replace an earlier one's instead of merging them — e.g. the
  // quality preset's _passthrough (its own unmapped fields) would silently
  // discard the printer preset's machine_start_gcode/machine_end_gcode.
  // Merge _passthrough across all sources field-by-field instead.
  const merged: OrcaConfig = {}
  let passthrough: PassthroughConfig | undefined
  for (const source of sources) {
    const { _passthrough, ...rest } = source
    Object.assign(merged, rest)
    if (_passthrough) passthrough = { ...passthrough, ..._passthrough }
  }
  if (passthrough) merged._passthrough = passthrough
  return merged
}

/**
 * The four corners of a rectangular bed, in the "XxY" vertex format
 * OrcaSlicer's `printable_area` uses and parsePrintableArea() reads back.
 * Shared by toEngineConfig() (which joins them into the flat comma-separated
 * string the engine's set_deserialize_strict expects) and
 * exportOrcaProfileJson() (which writes the JSON array form real profiles
 * use), so the two can't disagree about the winding or the origin corner.
 */
function bedCorners(x: number, y: number): string[] {
  return ['0x0', `${x}x0`, `${x}x${y}`, `0x${y}`]
}

/**
 * Nozzle diameters OrcaSlicer ships machine presets for. printerPresetName()
 * below builds "<model> <diameter> nozzle" from the configured diameter, so a
 * diameter outside this set names a preset that does not exist.
 */
const STOCK_NOZZLE_DIAMETERS: readonly number[] = [0.2, 0.25, 0.4, 0.6, 0.8]

/**
 * The name of the desktop OrcaSlicer printer preset this config corresponds
 * to, following OrcaSlicer's own machine-preset naming convention
 * "<printer model> <nozzle diameter> nozzle" (e.g. "Bambu Lab P1S 0.4
 * nozzle" — verified against the profiles shipped inside OrcaSlicer 2.4.2).
 *
 * Needed because a process/filament preset OrcaSlicer will actually accept
 * must name the printers it applies to in `compatible_printers`: without it
 * the preset is rejected outright ("process not compatible with printer",
 * CLI exit -17), and an empty list does not mean "any printer". Verified by
 * slicing with the exported files against a stock OrcaSlicer install.
 *
 * A guess, necessarily — this app never sees the user's actual preset list,
 * and a vendor whose presets don't follow the convention won't match. That
 * only costs the user editing one field in a plain-text JSON, whereas
 * omitting the key makes the export unusable for everyone.
 */
function printerPresetName(config: OrcaConfig): string | undefined {
  if (config.printer_model === undefined || config.nozzle_diameter === undefined) return undefined
  return `${config.printer_model} ${config.nozzle_diameter} nozzle`
}

/**
 * Translate OrcaConfig field names to the literal OrcaSlicer config option
 * names the WASM bridge expects, for the fields where they differ.
 *
 * The bridge sends every key straight through to
 * `g_config.set_deserialize_strict(key, value)` (orca-wasm/bridge/slicer.cpp)
 * with no key translation of its own — an unrecognized key is silently
 * skipped. `default_speed` and `enable_ironing` are OrcaConfig-only names
 * with no matching real option (verified against PrintConfig.cpp), so
 * everywhere they were previously set — every PRESETS entry (Draft/Standard/
 * Fine) and any imported 3MF with ironing — silently had no effect on the
 * actual slice.
 *
 * Call this once, right before JSON.stringify'ing the config for orc_init.
 */
export function toEngineConfig(config: OrcaConfig): Record<string, unknown> {
  const { default_speed, enable_ironing, bed_temperature, ...rest } = config as OrcaConfig & Record<string, unknown>
  const out: Record<string, unknown> = { ...rest }
  if (config.bed_size_x !== undefined && config.bed_size_y !== undefined) {
    out.printable_area = bedCorners(config.bed_size_x, config.bed_size_y).join(',')
  }
  if (bed_temperature !== undefined) {
    // OrcaSlicer/BambuStudio's real option names — "bed_temperature" isn't
    // in its PrintConfig schema, so set_deserialize_strict silently dropped
    // it and every slice used the engine's own baked-in default instead of
    // the UI value (confirmed: exported .3mf always had hot_plate_temp=45
    // regardless of this field, for every printer preset).
    out.hot_plate_temp = bed_temperature
    out.hot_plate_temp_initial_layer = bed_temperature
  }
  if (default_speed !== undefined) {
    // "Speed of inner wall" (PrintConfig.cpp) — the closest real equivalent
    // to a general/default print speed; OrcaSlicer has no single knob that
    // also scales infill/support speeds, those remain independently set.
    out.inner_wall_speed = default_speed
  }
  if (enable_ironing !== undefined) {
    out.ironing_type = enable_ironing ? 'top' : 'no ironing'
  }
  return out
}

/**
 * Why an exported bundle won't load in desktop OrcaSlicer, or null when
 * nothing is known to be wrong with it. For the export button to say so
 * instead of reporting a plain success.
 *
 * Both cases end in the same place: everything hangs off the stock preset
 * name printerPresetName() derives. The process/filament files are matched
 * against the printer's `inherits` and nothing else, and the machine file has
 * to inherit from a printer OrcaSlicer already has — so if that name is
 * missing or names nothing, the bundle is rejected outright (exit -17).
 * Measured against OrcaSlicer 2.4.2: an export with neither key fails exactly
 * like one naming the wrong printer.
 *
 * Slicing in this app is unaffected either way — the engine takes any nozzle
 * diameter and needs no preset names — which is why this is a note attached
 * to the download rather than a blocked button or a restricted input.
 */
export function describeExportCompatibility(config: OrcaConfig): string | null {
  if (printerPresetName(config) === undefined) {
    return (
      'Exported — but this profile does not say which printer model and nozzle it is for, so ' +
      'OrcaSlicer cannot tell what the presets belong to and will reject them. Set "inherits" in ' +
      'machine.json (and "compatible_printers" in the other two) to a printer you have.'
    )
  }
  const nozzle = config.nozzle_diameter
  if (nozzle !== undefined && !STOCK_NOZZLE_DIAMETERS.includes(nozzle)) {
    return (
      `Exported — but OrcaSlicer ships no preset for a ${nozzle} mm nozzle, so it will reject ` +
      'machine.json until you point its "inherits" at a printer you have.'
    )
  }
  return null
}

// Which real OrcaSlicer profile file a field belongs to — desktop OrcaSlicer
// profiles are split into separate print/filament/printer presets, each only
// populated with its own option set (see exportOrcaProfileBundle below).
type FieldCategory = 'process' | 'filament' | 'machine'

// OrcaSlicer profile field → OrcaConfig key mapping.
// OrcaSlicer often encodes numbers as strings (e.g. "0.2") and percentages as
// "15%". 'ironing' is its own type (see enable_ironing/ironing_type below):
// unlike bool, its true/false <-> string mapping isn't "1"/"0", it's the
// IroningType enum (s_keys_map_IroningType in PrintConfig.cpp).
//
// `importOnly` marks a field name that must never be written back out by
// exportOrcaProfileJson(). Two kinds qualify, and both have already shipped
// as export bugs once:
//   - Aliases: an alternative real OrcaSlicer/PrusaSlicer spelling of a field
//     whose canonical name is another entry here (e.g. `perimeters` for
//     `wall_loops`). Accepted on import, but exporting the alias instead of
//     the canonical name is at best noise.
//   - Synthetic OrcaConfig-only names with no matching real PrintConfig
//     option at all (`default_speed`, `bed_temperature`, `bed_shape`). These
//     are the dangerous ones: desktop OrcaSlicer silently drops unrecognized
//     keys, so exporting one loses the user's setting with no error.
// Flagging them explicitly (rather than relying on declaration order, which
// is how `default_speed`/`enable_ironing`/`bed_temperature` each leaked into
// exports in the first place) makes REVERSE_FIELD_MAP below order-independent.
const ORCA_FIELD_MAP: Record<
  string,
  {
    key: keyof OrcaConfig
    type: 'num' | 'pct' | 'bool' | 'str' | 'ironing'
    category: FieldCategory
    importOnly?: true
  }
> = {
  layer_height: { key: 'layer_height', type: 'num', category: 'process' },
  // The real FFF field is initial_layer_print_height — initial_layer_height
  // (no "print_") is a distinct SLA-only option (PrintConfigDef::init_sla_params)
  // that set_deserialize_strict on our FFF-only build silently ignores. See
  // OrcaConfig.initial_layer_print_height's own doc comment.
  initial_layer_print_height: { key: 'initial_layer_print_height', type: 'num', category: 'process' },
  wall_loops: { key: 'wall_loops', type: 'num', category: 'process' },
  perimeters: { key: 'wall_loops', type: 'num', category: 'process', importOnly: true }, // alias
  wall_generator: { key: 'wall_generator', type: 'str', category: 'process' },
  top_shell_layers: { key: 'top_shell_layers', type: 'num', category: 'process' },
  bottom_shell_layers: { key: 'bottom_shell_layers', type: 'num', category: 'process' },
  sparse_infill_density: { key: 'sparse_infill_density', type: 'pct', category: 'process' },
  fill_density: { key: 'sparse_infill_density', type: 'pct', category: 'process', importOnly: true }, // alias
  sparse_infill_pattern: { key: 'sparse_infill_pattern', type: 'str', category: 'process' },
  fill_pattern: { key: 'sparse_infill_pattern', type: 'str', category: 'process', importOnly: true }, // alias
  outer_wall_speed: { key: 'outer_wall_speed', type: 'num', category: 'process' },
  external_perimeter_speed: { key: 'outer_wall_speed', type: 'num', category: 'process', importOnly: true }, // alias
  // inner_wall_speed is the real OrcaSlicer field; `default_speed` is an
  // OrcaConfig-only synthetic name (see toEngineConfig's doc comment) kept
  // readable on import so profiles this app exported before the fix still
  // load, but never written back out.
  inner_wall_speed: { key: 'default_speed', type: 'num', category: 'process' },
  default_speed: { key: 'default_speed', type: 'num', category: 'process', importOnly: true },
  travel_speed: { key: 'travel_speed', type: 'num', category: 'process' },
  initial_layer_speed: { key: 'initial_layer_speed', type: 'num', category: 'process' },
  first_layer_speed: { key: 'initial_layer_speed', type: 'num', category: 'process', importOnly: true }, // alias
  brim_width: { key: 'brim_width', type: 'num', category: 'process' },
  brim_type: { key: 'brim_type', type: 'str', category: 'process' },
  skirt_loops: { key: 'skirt_loops', type: 'num', category: 'process' },
  skirt_distance: { key: 'skirt_distance', type: 'num', category: 'process' },
  raft_layers: { key: 'raft_layers', type: 'num', category: 'process' },
  seam_position: { key: 'seam_position', type: 'str', category: 'process' },
  enable_support: { key: 'enable_support', type: 'bool', category: 'process' },
  support_type: { key: 'support_type', type: 'str', category: 'process' },
  // ironing_type is the real OrcaSlicer field (s_keys_map_IroningType: "no
  // ironing"/"top"/"topmost"/"solid") — there is no real "ironing" or
  // "enable_ironing" option (verified against PrintConfig.cpp). enable_ironing
  // is an OrcaConfig-only simplified boolean toggle for the UI; the 'ironing'
  // type below is what translates it to/from the real enum string, mirroring
  // toEngineConfig's own enable_ironing -> ironing_type conversion.
  ironing_type: { key: 'enable_ironing', type: 'ironing', category: 'process' },
  fuzzy_skin: { key: 'fuzzy_skin', type: 'str', category: 'process' },
  fuzzy_skin_thickness: { key: 'fuzzy_skin_thickness', type: 'num', category: 'process' },
  fuzzy_skin_point_dist: { key: 'fuzzy_skin_point_dist', type: 'num', category: 'process' },
  // filament fields
  filament_type: { key: 'filament_type', type: 'str', category: 'filament' },
  nozzle_temperature: { key: 'nozzle_temperature', type: 'num', category: 'filament' },
  temperature: { key: 'nozzle_temperature', type: 'num', category: 'filament', importOnly: true }, // alias
  // hot_plate_temp is the real OrcaSlicer field — "bed_temperature" is not in
  // its PrintConfig schema at all, so exporting it silently loses the user's
  // bed temperature on import into desktop OrcaSlicer (the same failure mode
  // toEngineConfig documents for the engine side).
  hot_plate_temp: { key: 'bed_temperature', type: 'num', category: 'filament' },
  bed_temperature: { key: 'bed_temperature', type: 'num', category: 'filament', importOnly: true },
  fan_min_speed: { key: 'fan_min_speed', type: 'num', category: 'filament' },
  // machine fields
  printer_model: { key: 'printer_model', type: 'str', category: 'machine' },
  nozzle_diameter: { key: 'nozzle_diameter', type: 'num', category: 'machine' },
  printable_height: { key: 'printable_height', type: 'num', category: 'machine' },
  max_print_height: { key: 'printable_height', type: 'num', category: 'machine', importOnly: true }, // alias
  // OrcaConfig-only: real OrcaSlicer machine profiles describe bed geometry
  // solely through printable_area (parseOrcaProfileJson derives circle-ness
  // from its vertex count), and "rectangle"/"circle" aren't valid values for
  // any polygon field — so this is never written back out.
  bed_shape: { key: 'bed_shape', type: 'str', category: 'machine', importOnly: true },
  // bed size — handled separately via parsePrintableArea() below
}

/**
 * Parse bed size from OrcaSlicer's `printable_area` field.
 *
 * OrcaSlicer stores bed corners as an array of "XxY" strings, e.g.:
 *   ["0x0", "256x0", "256x256", "0x256"]
 * or as a flat comma-joined string: "0x0,256x0,256x256,0x256"
 *
 * Returns { dims: [maxX, maxY], circle: boolean } or null if unparseable.
 * When the polygon has more than 8 points it's treated as a circular bed.
 */
function parsePrintableArea(raw: unknown): { dims: [number, number]; circle: boolean } | null {
  let pts: string[]
  if (Array.isArray(raw)) {
    pts = raw.map(String)
  } else {
    const s = String(raw).trim()
    if (!s) return null
    pts = s.split(',')
  }
  let minX = Infinity,
    maxX = -Infinity,
    minY = Infinity,
    maxY = -Infinity
  let pointCount = 0
  for (const pt of pts) {
    const parts = pt.trim().split('x')
    if (parts.length < 2) continue
    const x = parseFloat(parts[0]),
      y = parseFloat(parts[1])
    if (!Number.isNaN(x) && !Number.isNaN(y)) {
      minX = Math.min(minX, x)
      maxX = Math.max(maxX, x)
      minY = Math.min(minY, y)
      maxY = Math.max(maxY, y)
      pointCount++
    }
  }
  // Bed size is the bounding-box extent. For corner-origin rectangular beds the
  // origin is (0,0) so this equals maxX/maxY; for center-origin circular/delta
  // beds (coords −r..+r) this gives the full diameter, not the radius.
  const sizeX = maxX - minX,
    sizeY = maxY - minY
  if (!(sizeX > 0) || !(sizeY > 0)) return null
  // Circular beds are approximated as polygons with many vertices in OrcaSlicer profiles.
  return { dims: [sizeX, sizeY], circle: pointCount > 8 }
}

export function parseOrcaProfileJson(json: string): Partial<OrcaConfig> {
  try {
    const raw = JSON.parse(json) as Record<string, unknown>

    // Support array-wrapped values (OrcaSlicer wraps some fields: ["0.2"])
    function unwrap(v: unknown): unknown {
      return Array.isArray(v) && v.length === 1 ? v[0] : v
    }

    const config: Partial<OrcaConfig> = {}

    for (const [field, meta] of Object.entries(ORCA_FIELD_MAP)) {
      if (!(field in raw)) continue
      const raw_val = unwrap(raw[field])
      // meta.key's associated OrcaConfig property type varies per field (number/boolean/string)
      // depending on meta.type, which TS can't correlate — widen to unknown so writes below
      // type-check without an `any` escape hatch.
      const out = config as Record<keyof OrcaConfig, unknown>
      if (meta.type === 'num') {
        const n = parseFloat(String(raw_val))
        if (!Number.isNaN(n)) out[meta.key] = n
      } else if (meta.type === 'pct') {
        // "15%" → 15, "0.15" → 15, "15" → 15 (OrcaSlicer integer), "1" → 1 (not 100)
        const s = String(raw_val).trim()
        const parsed = parseFloat(s)
        const n = s.endsWith('%') ? parsed : parsed < 1 ? parsed * 100 : parsed
        if (!Number.isNaN(n)) out[meta.key] = Math.round(n)
      } else if (meta.type === 'bool') {
        const s = String(raw_val).toLowerCase()
        out[meta.key] = s === '1' || s === 'true' || s === 'yes'
      } else if (meta.type === 'ironing') {
        // s_keys_map_IroningType: "no ironing"/"top"/"topmost"/"solid" — any
        // non-empty value other than "no ironing" means ironing is enabled.
        const s = String(raw_val).trim().toLowerCase()
        out[meta.key] = s !== '' && s !== 'no ironing'
      } else {
        out[meta.key] = String(raw_val)
      }
    }

    // ── Bed size ─────────────────────────────────────────────────────────────
    // OrcaSlicer machine profiles carry printable_area / bed_size for bed dims.
    if ('printable_area' in raw) {
      const result = parsePrintableArea(raw.printable_area)
      if (result) {
        config.bed_size_x = result.dims[0]
        config.bed_size_y = result.dims[1]
        if (result.circle && !config.bed_shape) config.bed_shape = 'circle'
      }
    } else if ('bed_size' in raw) {
      // Some older profiles use bed_size: ["256", "256"] or "256x256"
      const bs = unwrap(raw.bed_size)
      if (Array.isArray(bs) && bs.length >= 2) {
        const x = parseFloat(String(bs[0])),
          y = parseFloat(String(bs[1]))
        if (!Number.isNaN(x) && x > 0) config.bed_size_x = x
        if (!Number.isNaN(y) && y > 0) config.bed_size_y = y
      } else {
        const result = parsePrintableArea(bs)
        if (result) {
          config.bed_size_x = result.dims[0]
          config.bed_size_y = result.dims[1]
          if (result.circle && !config.bed_shape) config.bed_shape = 'circle'
        }
      }
    }

    // ── Passthrough for unmapped OrcaSlicer fields ───────────────────────────
    // Collect every field not already processed so it can be forwarded verbatim
    // to the WASM slicer (which accepts any DynamicPrintConfig key) — except
    // including genuinely multi-extruder machine profiles: the crash that used
    // to make those unsafe was our own serialization fusing their multi-value
    // options into one entry, not the engine — see the array handling below
    // and issue #140.
    {
      const SKIP_META = new Set([
        'type',
        'name',
        'inherits',
        'from',
        'version',
        'description',
        '__proto__',
        'constructor',
        'prototype',
      ])
      // Keep printable_area verbatim so non-rectangular and offset beds survive
      // import -> export. toEngineConfig supplies a rectangular fallback for
      // built-in presets, while this passthrough value takes precedence later.
      const SKIP_BED = new Set(['bed_size'])
      const alreadyMapped = new Set(Object.keys(ORCA_FIELD_MAP))
      const passthrough: PassthroughConfig = Object.create(null) as PassthroughConfig
      for (const [field, val] of Object.entries(raw)) {
        if (SKIP_META.has(field) || SKIP_BED.has(field)) continue
        if (val === null || val === undefined) continue
        // Mapped fields normally stay out of the passthrough — they already
        // reached the engine through their OrcaConfig key. Multi-value ones are
        // the exception: ORCA_FIELD_MAP collapses an array to a single scalar
        // for the UI (nozzle_diameter ["0.4","0.4"] -> 0.4), which would tell
        // the engine a dual-nozzle machine has one nozzle. Forward those as
        // arrays too so the engine sees the real per-extruder values; the
        // scalar keeps driving the UI. See #140.
        const isMultiValue = Array.isArray(val) && val.length > 1
        if (alreadyMapped.has(field) && !isMultiValue) continue
        if (Array.isArray(val)) {
          // OrcaSlicer wraps values in arrays (single-extruder: ["0.8"], multi: ["0.8","1.0"]).
          // Forward the array *as an array* and let the WASM bridge join it: the
          // separator is a property of the option's type (';' for coStrings,
          // '#' between coPointsGroups groups, ',' for the rest), and only the
          // engine's own option registry knows which is which. Joining here with
          // a single guessed separator silently fused every multi-value string
          // and points-group option into one entry — see #140 and
          // json_array_to_config_string() in orca-wasm/bridge/slicer.cpp.
          const items = val
            .filter((x) => x !== null && x !== undefined)
            .map((x) => (typeof x === 'boolean' ? (x ? '1' : '0') : String(x)))
          // Single-entry arrays collapse to a plain string exactly as before —
          // the two are equivalent once the bridge joins them, and keeping the
          // old shape avoids churning every ordinary single-extruder field.
          // An empty one is dropped rather than stored as "", also as before:
          // real leaf profiles carry [""] for every option they inherit rather
          // than override, and buildConfig() merges _passthrough field by field
          // with later layers winning — so a stored "" blanks out the built-in
          // preset's value for that key instead of leaving it alone. A
          // *multi*-entry array keeps its empties: there the length is load-
          // bearing (filament_start_gcode: ["", ""] is what sizes the vector).
          if (items.length === 1) {
            if (items[0] !== '') passthrough[field] = items[0]
          } else if (items.length > 1) passthrough[field] = items
          continue
        }
        const sv = typeof val === 'boolean' ? (val ? '1' : '0') : String(val)
        if (sv !== '') passthrough[field] = sv
      }
      if (Object.keys(passthrough).length > 0) config._passthrough = passthrough
    }

    return config
  } catch {
    return {}
  }
}

// Reverse of ORCA_FIELD_MAP: for each internal OrcaConfig key, the real
// OrcaSlicer field name to write on export. Built by skipping every
// `importOnly` entry rather than by taking the first field seen for a key —
// declaration order is not a safe signal here, and relying on it is exactly
// how default_speed, enable_ironing and bed_temperature each shipped as the
// exported name for a field OrcaSlicer doesn't have. A key whose only entry
// is importOnly (e.g. bed_shape) is deliberately absent, and so never
// exported at all.
const REVERSE_FIELD_MAP: Partial<Record<keyof OrcaConfig, string>> = {}
for (const [field, meta] of Object.entries(ORCA_FIELD_MAP)) {
  if (meta.importOnly) continue
  if (meta.key in REVERSE_FIELD_MAP) {
    throw new Error(
      `ORCA_FIELD_MAP: "${field}" and "${REVERSE_FIELD_MAP[meta.key]}" both claim to be the exported name for ` +
        `"${meta.key}" — exactly one entry per key may omit importOnly.`,
    )
  }
  REVERSE_FIELD_MAP[meta.key] = field
}

/**
 * `_passthrough` fields that must never reach an exported file, however they
 * were spelled in the profile they came from.
 *
 * Both of these name (or test for) the printer the *imported* profile was
 * written for, which is not necessarily the printer being exported here — a
 * process preset imported from a Creality profile carries
 * `compatible_printers: ["Creality Ender-3 0.4 nozzle"]`, and passing it
 * through means the exported bundle claims compatibility with a printer its
 * own machine.json isn't. OrcaSlicer then rejects the whole combination
 * ("process not compatible with printer", CLI exit -17) — the exact failure
 * the derived `compatible_printers` below exists to prevent. Dropping them
 * lets the derived value stand.
 */
const PASSTHROUGH_EXPORT_DENYLIST = new Set(['compatible_printers', 'compatible_printers_condition'])

/**
 * Serialize the current in-app config back into a single OrcaSlicer-
 * compatible profile JSON of one type (`process`/`filament`/`machine`) — the
 * mirror of parseOrcaProfileJson(). Only fields belonging to `category` are
 * written (canonical OrcaSlicer field names via REVERSE_FIELD_MAP), matching
 * how real OrcaSlicer print/filament/printer presets are three genuinely
 * separate option sets, not one flat file — a "process" preset with e.g.
 * nozzle_diameter (a machine-only option) mixed in isn't a shape desktop
 * OrcaSlicer's preset bundles ever produce themselves. Percentages are
 * written as "NN%" and printable_area as bed-corner strings, so each file is
 * also loadable by desktop OrcaSlicer as a user preset of that type.
 *
 * `_passthrough` fields can't be reliably attributed to a single category —
 * they arrive pre-merged from potentially multiple sources (buildConfig
 * merges every preset layer's _passthrough together; parseOrcaProfileJson
 * dumps every unmapped field from whichever single file was imported into
 * one bag) — so they're written to every category's file rather than
 * risking silently dropping one. A passthrough field that doesn't belong to
 * a given file's category is simply an unrecognized key there, same as any
 * other key set_deserialize_strict doesn't know.
 *
 * A field this config leaves unset is deliberately absent from the output
 * rather than filled in from DISPLAY_DEFAULTS: unset means "whatever the
 * engine defaults to", and desktop OrcaSlicer resolves an absent key from
 * that same default, so omitting it is what keeps the exported preset
 * slicing the way this app sliced. That only holds while DISPLAY_DEFAULTS
 * agrees with the engine — see its own comment.
 *
 * Exported by exportOrcaProfileBundle() below for actual use; kept as its
 * own function (rather than inlined) so tests can assert one category's
 * output directly.
 */
export function exportOrcaProfileJson(config: OrcaConfig, name: string, category: FieldCategory): string {
  const { _passthrough, bed_size_x, bed_size_y, ...rest } = config
  const out: Record<string, unknown> = {
    type: category,
    name,
    from: 'User',
  }
  for (const [orcaKey, value] of Object.entries(rest)) {
    if (value === undefined || value === null) continue
    const field = REVERSE_FIELD_MAP[orcaKey as keyof OrcaConfig]
    if (!field) continue
    const meta = ORCA_FIELD_MAP[field]
    if (meta.category !== category) continue
    out[field] =
      meta.type === 'pct'
        ? `${value}%`
        : meta.type === 'ironing'
          ? value
            ? 'top'
            : 'no ironing'
          : typeof value === 'boolean'
            ? value
              ? '1'
              : '0'
            : String(value)
  }
  if (category === 'filament' && config.bed_temperature !== undefined) {
    // OrcaSlicer splits bed temperature into the steady-state and first-layer
    // options; the UI has one knob, so both get it — mirroring exactly what
    // toEngineConfig() sends to the engine, so an exported profile slices the
    // same way in desktop OrcaSlicer as it did here.
    out.hot_plate_temp_initial_layer = String(config.bed_temperature)
  }

  // Passthrough goes on *before* the derived keys below, not after. A
  // passthrough value describes the profile it was imported from; the derived
  // keys describe the selection actually being exported, so where the two
  // collide the derived one has to win. (Applying it last is how an imported
  // profile's foreign `compatible_printers` used to silently replace the
  // derived one and make the bundle unloadable.) printable_area is the one
  // deliberate exception, re-applied further down.
  if (_passthrough) {
    for (const [field, value] of Object.entries(_passthrough)) {
      if (PASSTHROUGH_EXPORT_DENYLIST.has(field)) continue
      out[field] = value
    }
  }

  const printer = printerPresetName(config)
  if (printer && (category === 'process' || category === 'filament')) {
    // Exactly one entry, and it has to be the *stock* preset name, because
    // that is the only string this list is ever compared against.
    //
    // Measured against OrcaSlicer 2.4.2's CLI (the path this bundle is for):
    // the gate is OrcaSlicer.cpp's own `process_compatible` loop, not
    // Preset.cpp's is_compatible_with_printer(), and it tests each entry
    // against `new_printer_system_name` — the printer preset's `inherits`
    // value, never the preset's own name. Adding the exported machine file's
    // name here is therefore inert: verified, a list containing only that
    // name is rejected (exit -17) even though that file *is* the printer
    // being loaded. Its `inherits` (set below) is what makes the match.
    //
    // An absent or empty list is not "compatible with anything" either — the
    // loop simply never matches. Verified: dropping the key fails the same
    // -17. (Preset.cpp's separate GUI-side check does treat an empty list as
    // compatible-with-all, which is what makes this easy to get wrong.)
    out.compatible_printers = [printer]
  }
  if (printer && category === 'machine') {
    // A machine preset has to derive from a printer OrcaSlicer already knows;
    // a standalone one is rejected the same way an uncompatible process is.
    // Inheriting from the stock preset of the same model makes this a normal
    // user printer preset — verified end to end: the exported file slices,
    // and printer_model/nozzle_diameter/printable_height come from here.
    out.inherits = printer
  }
  if (category === 'machine') {
    // An imported profile's own printable_area wins over the rectangle
    // derived from bed_size_x/y, so non-rectangular and offset beds survive
    // import -> export (see parseOrcaProfileJson's SKIP_BED comment). Real
    // machine profiles use the array form, which the passthrough now preserves
    // as-is; the string branch still handles a value that reached us already
    // flattened (a hand-written profile, or an older persisted setting).
    const imported = _passthrough?.printable_area
    if (imported !== undefined) {
      out.printable_area = Array.isArray(imported)
        ? imported
        : imported
            .split(',')
            .map((vertex) => vertex.trim())
            .filter(Boolean)
    } else if (bed_size_x !== undefined && bed_size_y !== undefined) {
      out.printable_area = bedCorners(bed_size_x, bed_size_y)
    }
  }
  return JSON.stringify(out, null, 2)
}

/**
 * Export the current settings as a full OrcaSlicer preset bundle — one file
 * per real preset type (process/filament/machine), matching how desktop
 * OrcaSlicer itself stores and imports presets (see exportOrcaProfileJson's
 * own doc comment for why a single flat file can't represent this). Used by
 * SettingsPanel's "Export" button, which zips the three files together so
 * the whole bundle downloads as one action.
 */
export function exportOrcaProfileBundle(
  config: OrcaConfig,
  baseName: string,
): { filename: string; category: FieldCategory; json: string }[] {
  return (['process', 'filament', 'machine'] as const).map((category) => ({
    filename: `${category}.json`,
    category,
    json: exportOrcaProfileJson(config, `${baseName} (${category})`, category),
  }))
}
